services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - '127.0.0.1:3060:3000'
    extra_ports:
      - "host.docker.internal:172.25.0.1"
    env_file:
      - .env
    volumes:
      - ./public:/app/public
    restart: unless-stopped

