services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - '3060:3000'
    env_file:
      - .env
    volumes:
      - ./public:/app/public
    restart: unless-stopped

